# vocabulario de palabras
vocabylary = {
    'round': 'redondo',
    'short': 'corto',
    'long': 'largo',
    'river': 'rio',
    'highway': 'carretera/avendia',
    'newspaper': 'periodico',
    'number': 'numero',
    'office': 'officina',
    'paper': 'papel',
    'picture': 'foto',
    'passes': 'pasa',
    'through': 'a travez de',
    'interior': 'interior',
    'student': 'estudiante',
    'sugar': 'azucar',
    'table': 'mesa',
    'that': 'eso',
    'this': 'esto',
    'village': 'aldea',
    'so': 'entonces/por lo tanto',
    'clock': 'reloj #de pared',
    'country': 'pais',
    'desk': 'escritorio',
    'door': 'puerta',
    'france': 'francia',
    'french': 'frances',
    'hat': 'sombrero',
    'italy': 'italia',
    'language': 'idioma/lenguaje',
    'lesson': 'lección',
    'apartment': 'apartamento',
    'beer': 'cerveza',
    'bottle': 'botella',
    'brown': 'marron',
    'calendar': 'calendario',
    'phone': 'telefono',
    'small': 'pequeño',
    'station': 'estación',
    'street': 'calle',
    'to park': 'aparcar',
    'good': 'bueno',
    'house': 'casa',
    'name': 'nombre',
    'pen': 'boligrafo',
    'pencil': 'lapiz',
    'married': 'casado/a',
    'nationality': 'nacionalidad',
    'how': 'como',
    'single': 'soletero/a',
    'politician': 'politico',
    'family': 'familia',
    'goodbye': 'adios',
    'green': 'verde',
    'here': 'aqui',
    'horse': 'caballo',
    'rich': 'rico',
    'husband': 'marido',
    'italian': 'italiano',
    'man': 'hombre',
    'notebook': 'cuaderno',
    'translator': 'traductor',
    'attractive': 'atractivo',
    'town': 'pueblo',
    'region': 'region',
    'continent': 'continente',
    'community': 'comunidad',
    'state': 'estado',
    'capital': 'capital',
    'cost': 'costa',
    'province': 'provincia',
    'german': 'aleman',
    'plate': 'plato #recipiente',
    'dish': 'plato #plato_de_frijoles',
    'pretty': 'bonita/o',
    'school': 'escuela/colegio',
    'ship': 'barco',
    'city': 'ciudad',
    'class': 'clase',
    'dog': 'perro',
    'fine': 'bien',
    'girl': 'chica',
    'book': 'libro',
    'boy': 'chico',
    'car': 'carro',
    'cat': 'gato',
    'chair': 'silla',
    'apple': 'manzana',
    'bad': 'malo',
    'big': 'grande',
    'black': 'negro',
    'blue': 'azul',
    'airport': 'aeropuerto',
    'answer': 'respuesta',
    'bed': 'cama',
    'box': 'caja',
    'cigarrete': 'cigarrillo',
    'correct': 'correcto',
    'cup': 'taza #grande',
    'mug': 'taza #pequeña',
    'december': 'diciembre',
    'dress': 'vestido',
    'easy': 'facil',
    'british': 'britanico',
    'english': 'ingles',
    'more': 'mas',
    'too': 'tambien',
    'happy': 'feliz',
    'tv': 'television',
    'studio': 'estudio #estudio_de_grabacion',
    'either': 'tampoco',
    'business': 'negocios',
    'sitting': 'sentado',
    'need': 'necesidad',
    'afternoon': 'tarde #por la tarde',
    'bedroom': 'dormitorio/habitacion',
    'bird': 'pajaro',
    'clean': 'limpio',
    'lawyer': 'abogado',
    'carpenter': 'carpintero',
    'engineer': 'ingeniero',
    'policeman': 'policia',
    'ugly': 'feo',
    'child': 'niño/a',
    'nourse': 'enfermero/a',
    'tall': 'alto',
    'slim': 'delgado',
    'overweight': 'sobrepeso',
    'coffe': 'cafe #bebida',
    'handbag': 'bolso',
    'homework': 'tarea/deberes',
    'hot': 'caliente',
    'now': 'ahora',
    'sick': 'efermo/a',
    'fat': 'gordo',
    'crazy': 'loco',
    'little': 'poco',
    'lot': 'mucho',
    'hour': 'hora',
    'in front of': 'delante de',
    'magazine': 'revista',
    'map': 'mapa',
    'narrow': 'angosto/estrecho',
    'dificult': 'dificil',
    'for': 'por/en',
    'dentist': 'dentista',
    'doctor': 'medico',
    'math': 'matematicas',
    'history': 'historia',
    'physics': 'fisica #area',
    'biology': 'biologia',
    'literature': 'literatura',
    'latin': 'latino/a',
    'one': 'uno',
    'two': 'dos',
    'thre': 'tres',
    'four': 'cuatro',
    'five': 'cinco',
    'six': 'seis',
    'expensive': 'caro',
    'seven': 'siete',
    'eight': 'ocho',
    'nine': 'nueve',
    'ten': 'diez',
    'new': 'nuevo',
    'next to': 'junto a/al lado de',
    'nice': 'lindo/simpatico',
    'secretary': 'secretaria',
    'shop': 'tienda'
}